# Generated by Django 3.1.3 on 2020-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201116_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_user',
            name='user_introduce',
            field=models.TextField(null=True, verbose_name='简历'),
        ),
    ]
